### ISSUE TITLE
riot 3.1.x compatible?

### ISSUE THREAD

**Issue by oldlastman** [Scritik/prestui#12]
hi,
i'm install prestui in my proyect and i set riot+compiler.min load but i receive this error:
Uncaught TypeError: Cannot read property 'opts' of undefined

prestui is compatible with recent versions of riot?

if not, what version i must use?

thanks

**Comment by Scritik** [comment]
Hi,

No, not yet. I'm still working on it.

You can use the 2.6 version until it's done:

`https://cdnjs.cloudflare.com/ajax/libs/riot/2.6.7/riot+compiler.min.js`
