### ISSUE TITLE
switch or select error elements inside tabs

### ISSUE THREAD

**Issue by oldlastman** [Scritik/prestui#13]
i'm trying this code

`	<ps-tab label="test"  id="tab_base" icon="icon-AdminParentModules" img="../img/t/AdminBackup.gif" fa="cogs">
		<ps-switch name="switch" label="Switch" yes="Yes" no="No" active="false"></ps-switch>
		<ps-select label="Select input" name="ps_select" chosen='true'>
        <option value="test">test</option>
        <option value="test2">test2</option>
    </ps-select>
	    </ps-tab>`

and don't render well

- switch: never show  correct status
- select: dont show options

there is some thing wrong in my code?

thanks

**Comment by oldlastman** [comment]
maybe its related with panel attribute?
i just put
`<ps-tab label="test" id="tab_base" icon="icon-AdminParentModules" img="../img/t/AdminBackup.gif" fa="cogs" panel="false">`
and swtich works
but select not work

**Comment by Scritik** [comment]
Hi @oldlastman,

The panel attribute is just here to wrap the content into a panel. Are you sure that you content is in a form (like specified in the doc)?

**Comment by oldlastman** [comment]
hi! thanks for your answer
yes i'm using form tag

this is an full example
sorry code not show all tags
http://pastebin.com/8UTfVNgN

```
< ps-panel >
	< form class="form-horizontal" name="module_form" method="post" action="">
< ps-tabs position="left">
    < ps-tab label="Tab 1" active="true" id="tab1" icon="icon-AdminParentModules" img="../img/t/AdminBackup.gif" fa="cogs">
			< ps-switch name="switch" label="Switch" yes="Yes" no="No" active="true">< /ps-switch>
			< ps-select label="Select input" name="ps_select" chosen="true">
					< option value="testito">testito< /option>
					< option value="test2">test2< /option>
			< /ps-select>
    < /ps-tab>
    < ps-tab label="Tab 2" id="tab2" icon="icon-AdminParentModules" img="../img/t/AdminBackup.gif">
			< ps-switch name="switch2" label="Switch2" yes="Yes" no="No" active="false">< /ps-switch>
			< ps-select label="Select input2" name="ps_select2" chosen="true">
					< option value="testito3">testito3< /option>
					< option value="test4">test4< /option>
			< /ps-select>
    < /ps-tab>
    < ps-tab label="Tab 3" id="tab3">
        // content 3
    < /ps-tab>
< /ps-tabs>
< ps-panel-footer>
		< ps-panel-footer-submit title="Guardar cambios" icon="process-icon-save" direction="right" name="submitAtt_UserGroupAssignModule">< /ps-panel-footer-submit>
< /ps-panel-footer>
< /form>
< /ps-panel>
```

if i put:
- tab "panel" attribute to false
- just one select "chosen" attribute=true and others as false
it looks all work well,
i'm mess up all tags.. or some behavior it's not fine tuned?

thanks

**Comment by Scritik** [comment]
Sorry for the delay. Do you still have the issue? I will try to keep a look at this asap.

Also, I just made a PR with Riot 3 support, if you want to give it a try. It took me longer than expected but it's finally here.

**Comment by Scritik** [comment]
I found the issues @oldlastman!

It was not your code and fixed both on the riot3 PR if you want to take a look at it.

**Comment by Scritik** [comment]
I merged the PR, and will release a new version asap. Please use this new version, with Riot3.
