### ISSUE TITLE
Didn't works

### ISSUE THREAD

**Issue by tanzo** [Scritik/prestui#18]
Sorry, we have followed the instructions without success... Is still valid the documentation and the files?

Thanks

**Comment by Scritik** [comment]
Can you show me some of your code where you include all the necessary files? Which version of Riot do you use? Do you have any javascript error?

**Comment by tanzo** [comment]
Hi Emmanuel, I have re-tried with a dummy module. It was my fault because I've included twice the riot from the CDN, the riot+compiler and the riot (again ^^").
Yesterday I was very tired, I'm sorry and thanks for the quick answer ;)

**Comment by Scritik** [comment]
no problem ;)
