### ISSUE TITLE
Prefix is needed for attribute

### ISSUE THREAD

**Issue by maniT4c** [Scritik/prestui#4]
If we use id, name or class for target element the orginal element (<ps-input-text> for exemple will be targeted.

Like this
<ps-input-text class="myInput">

$('.myinput') will target generated input AND the orginal <ps-input-text> element.

It's worse with id (see my request) because jquery stop on first id founded.

**Comment by Scritik** [comment]
(yep, never too late :))

I don't think adding IDs inside PrestUI is a good idea. If you want to add an ID, it's better to have it on the riot tag, and then access the child you want:

```
$('#my-tag input[name=title]')
```

For the classes, this is the same. You are not supposed to customize the content of the tag. If you really need to, you can add an ID or a class on the riot tag and add your CSS/JS depending on that.

Finally, for the name, is it really such a big issue? When you want to access an element by its name, it's better to add the input type before, like in my previous element, no?
