### ISSUE TITLE
Create tables

### ISSUE THREAD

**Issue by DavidSoy** [Scritik/prestui#7]
We are implementing the standard UX using the PrestUI library. We are showing a table using the example of github (https://github.com/Scritik/prestui/wiki/Tables) but the table does not show the rows; it only shows the header. Debbugging the code for displaying the table (ps-table.tpl) we found that the error should be on the line 66:

<pre>
<tbody>
    <tr class="odd" each={ row, i in this.rows }>
        <td each={ value, key in this.columns_keys } class="{ this.columns_classes[key] }">
            { row[value] }
        </td>
        <td if={ this.primary_action }>
            <div class="btn-group-action">
                <div class="btn-group pull-right">
                    <a href="{ this.base_action_url }&action={ this.primary_action.action }&{ this.identifier }={ row[this.identifier] }" title="{ this.primary_action.title }" class="edit btn btn-default">
                        <i class="icon-{ this.primary_action.icon }"></i> { this.primary_action.title }
                    </a>
                    <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-caret-down"></i>&nbsp;
                    </button>
                    <ul class="dropdown-menu" if={ this.secondary_actions }>
                        <li each={ elem, index in this.secondary_actions }>
                        <a href="{ this.base_action_url }&action={ elem.action }&{ this.identifier }={ row[this.identifier] }" title="{ elem.title }">
                                <i class="icon-{ elem.icon }"></i> { elem.title }
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </td>
    </tr>
</tbody>
</pre>

Specifically in the loop columns nested within the loop of the rows. The variable this.columns_keys is apparently being ignored because is nested within a loop. If we change the variable this.columns_keys and we put the variable row in its place, declared in the upper loop, the rows of the table are shown.

This also happens with the action buttons for each row. The condition of the line 69 (if={ this.primary_action }) is always false because that variable seems not to exist in that loop.

We would appreciate a more extensive documentation and examples of PrestUI to display tables.

**Comment by Scritik** [comment]
Hi,

Can you show me a PHP sample to reproduce you bug? I'm using ps-table in several modules and I don't have any issue with it and I can't really understand exactly where is this issue.
Also, can you test with the dev branch? I have recently made a patch on empty tables but if I understand well you case, this is not the solution to your problem.

Regarding the documentation, what do you need more? You have a PHP sample on how to create the array and then a Smarty sample to display the array.
